name: SonarCloud Analysis
on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches.

      - name: SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.organization=yavuzdeveloper
            -Dsonar.projectKey=yavuzdeveloper_artwork-app
