name: OWASP ZAP Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Next.js app
        run: |
          npm ci
          npm run build
          npm run start &  # Start the Next.js app	
          sleep 15  # Wait for the app to start

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:3000" # Next.js app URL
